name: sarc-scraper-ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t sarc-scraper-ci-cd:latest .
      - name: Upload to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          SOURCE: './'
          REMOTE_HOST: 'ec2-18-217-171-64.us-east-2.compute.amazonaws.com'
          REMOTE_USER: 'ec2-user'
          TARGET: '/home/ec2-user'
